jmf_grid:

    #template_path:         '@JmfGrid/grid.html.twig'
    #twig_functions_prefix: 'jmf_'

    grids:
        articles:
            grid:
                variables:
                    entityType: 'article'
            rows:
                link: '{{ path("article.read", {"id": _item.id} ) }}'
                variables:
                    entityId: '{{ _item.id }}'
            columns:
                -
                    label:  'title'
                    source: 'title'
                -
                    preset: 'date'
                    source: 'date'
                -
                    preset: 'button_show'
        users:
            grid:
                variables:
                    entityType: 'user'
            rows:
                link: '{{ path("user.read", {"id": _item.id} ) }}'
                variables:
                    entityId: '{{ _item.id }}'
            columns:
                -
                    label:  'Last Name'
                    source: 'lastName'
                -
                    label:  'First Name'
                    source: 'firstName'
                -
                    preset: 'gender'
                -
                    label:  'Birth Date'
                    source: 'startDate'
                -
                    preset: 'button_show'
                -
                    preset: 'button_edit'
