<?php

declare(strict_types=1);

use Jmf\Grid\Twig\GridExtension;
use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->fixXmlConfig('grid')
        ->children()
            ->arrayNode('grids')
                ->defaultValue([])
                ->info('Grid definitions.')
                ->useAttributeAsKey('id')
                ->arrayPrototype()
                    ->children()
                        ->arrayNode('grid')
                            ->addDefaultsIfNotSet()
                            ->fixXmlConfig('argument')
                            ->fixXmlConfig('variable')
                            ->children()
                                ->arrayNode('arguments')
                                    ->useAttributeAsKey('key')
                                    ->scalarPrototype()->end()
                                ->end()
                                ->arrayNode('variables')
                                    ->useAttributeAsKey('key')
                                    ->variablePrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('rows')
                            ->addDefaultsIfNotSet()
                            ->fixXmlConfig('attribute')
                            ->fixXmlConfig('variable')
                            ->children()
                                ->scalarNode('link')->defaultNull()->end()
                                ->arrayNode('attributes')
                                    ->info('HTML attributes to add to the <tr> tag. Values are Twig template strings.')
                                    ->useAttributeAsKey('key')
                                    ->scalarPrototype()->end()
                                ->end()
                                ->arrayNode('variables')
                                    ->useAttributeAsKey('key')
                                    ->variablePrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('columns')
                            ->isRequired()
                            ->requiresAtLeastOneElement()
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('align')->defaultNull()->end()
                                    ->scalarNode('label')->defaultNull()->end()
                                    ->scalarNode('source')->defaultNull()->end()
                                    ->scalarNode('template')->defaultNull()->end()
                                    ->scalarNode('preset')->defaultNull()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('footer')
                            ->arrayPrototype()
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('align')->defaultNull()->end()
                                        ->scalarNode('template')->defaultNull()->end()
                                        ->integerNode('merge')->defaultNull()->min(1)->end()
                                        ->scalarNode('value')->defaultNull()->end()
                                        ->scalarNode('preset')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->scalarNode('template_path')
                ->info('Grid template path.')
                ->defaultValue('@JmfGrid/grid.html.twig')
            ->end()
            ->scalarNode('twig_functions_prefix')
                ->info('Twig functions prefix.')
                ->defaultValue(GridExtension::PREFIX_DEFAULT)
            ->end()
        ->end()
    ;
};
