services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\Grid\:
        resource: '../src/'

    Jmf\Grid\Grid\GridGeneratorFactory:
        arguments:
            $gridConfigs: '%jmf_grid.grid_configurations%'

    Jmf\Grid\Grid\GridGenerator:
        factory: ['@Jmf\Grid\Grid\GridGeneratorFactory', 'create']

    Jmf\Grid\Twig\GridExtension:
        arguments:
            $templatePath: '%jmf_grid.template_path%'
            $prefix:       '%jmf_grid.twig_functions_prefix%'
        tags:
            - 'twig.extension'
