services:

    _defaults:
        autoconfigure: true
        autowire:      true

    Jmf\Grid\:
        resource: '../src/'

    Jmf\Grid\Configuration\Grid\CacheableGridConfigurationRepository:
        arguments:
            $gridConfigs: '%jmf_grid.grid_configurations%'
            $wrapped:     '@Jmf\Grid\Configuration\Grid\GridConfigurationRepository'

    Jmf\Grid\Configuration\Grid\GridConfigurationRepository:
        arguments:
            $gridConfigs: '%jmf_grid.grid_configurations%'

    Jmf\Grid\Configuration\Grid\GridConfigurationLoaderInterface:
        alias: Jmf\Grid\Configuration\Grid\CacheableGridConfigurationLoader

    Jmf\Grid\Twig\GridExtension:
        arguments:
            $templatePath: '%jmf_grid.template_path%'
            $prefix:       '%jmf_grid.twig_functions_prefix%'
        tags:
            - 'twig.extension'
