name: Symfony CI
on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]
jobs:
    test:
        name:    Run tests on PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.3', '8.4', '8.5' ]
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions:  mbstring, xml, ctype, iconv, intl
                    coverage:    none
            -
                name: Validate composer.json and composer.lock
                run:  composer validate --strict
            -
                name: Install Composer dependencies
                run:  composer install --prefer-dist --no-progress
            -
                name: Run PHPLint
                run:  bin/phplint
            -
                name: Run PHPStan
                run:  bin/phpstan
            -
                name: Run Rector
                run:  bin/rector --dry-run
            -
                name: Run PHPUnit tests
                run:  bin/phpunit
